[package]
name = "basic-web-server"
version = "0.1.0"
edition = "2021"

[dependencies]
threadpool = "1.8.1"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
rustls = "0.23.20"
webpki-roots = "0.26.7"
tokio-rustls = "0.26.1"